// The control plane. This is the only place gRPC appears in Forge, and
// the boundary is strict: jobs NEVER travel here. Work moves through
// Redis, where it is durable and claimable; this stream carries the small
// bidirectional truth that HTTP polling handles badly -- workers pushing
// live stats up, operators pushing drain/pause/resize down, with sub-
// second latency and no polling loop on either side. That push-down
// direction is what earns gRPC its place: "drain worker 3 now" over
// polled HTTP means waiting a poll interval; over a live stream it means
// now.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Stats
	//	*WorkerMessage_Ack
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *WorkerHello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetStats() *WorkerStats {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *WorkerMessage) GetAck() *CommandAck {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *WorkerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Stats struct {
	Stats *WorkerStats `protobuf:"bytes,2,opt,name=stats,proto3,oneof"`
}

type WorkerMessage_Ack struct {
	Ack *CommandAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Stats) isWorkerMessage_Msg() {}

func (*WorkerMessage_Ack) isWorkerMessage_Msg() {}

type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Concurrency   int32                  `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Types         []string               `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerHello) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WorkerHello) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *WorkerHello) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type WorkerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        int32                  `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Target        int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	Processed     uint64                 `protobuf:"varint,3,opt,name=processed,proto3" json:"processed,omitempty"`
	Utilization   float64                `protobuf:"fixed64,4,opt,name=utilization,proto3" json:"utilization,omitempty"`
	Paused        bool                   `protobuf:"varint,5,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStats) Reset() {
	*x = WorkerStats{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStats) ProtoMessage() {}

func (x *WorkerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStats.ProtoReflect.Descriptor instead.
func (*WorkerStats) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerStats) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *WorkerStats) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *WorkerStats) GetProcessed() uint64 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *WorkerStats) GetUtilization() float64 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *WorkerStats) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Command_Drain
	//	*Command_Pause
	//	*Command_Resume
	//	*Command_SetConcurrency
	Cmd           isCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetCmd() isCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Command) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *Command) GetPause() *Pause {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *Command) GetResume() *Resume {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *Command) GetSetConcurrency() *SetConcurrency {
	if x != nil {
		if x, ok := x.Cmd.(*Command_SetConcurrency); ok {
			return x.SetConcurrency
		}
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_Drain struct {
	Drain *Drain `protobuf:"bytes,2,opt,name=drain,proto3,oneof"` // stop fetching, finish in-flight, exit
}

type Command_Pause struct {
	Pause *Pause `protobuf:"bytes,3,opt,name=pause,proto3,oneof"` // stop fetching, stay alive
}

type Command_Resume struct {
	Resume *Resume `protobuf:"bytes,4,opt,name=resume,proto3,oneof"`
}

type Command_SetConcurrency struct {
	SetConcurrency *SetConcurrency `protobuf:"bytes,5,opt,name=set_concurrency,json=setConcurrency,proto3,oneof"` // live-resize the pool
}

func (*Command_Drain) isCommand_Cmd() {}

func (*Command_Pause) isCommand_Cmd() {}

func (*Command_Resume) isCommand_Cmd() {}

func (*Command_SetConcurrency) isCommand_Cmd() {}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

type Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{6}
}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{7}
}

type SetConcurrency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int32                  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConcurrency) Reset() {
	*x = SetConcurrency{}
	mi := &file_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConcurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConcurrency) ProtoMessage() {}

func (x *SetConcurrency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConcurrency.ProtoReflect.Descriptor instead.
func (*SetConcurrency) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *SetConcurrency) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\x10forge.control.v1\"\xb6\x01\n" +
	"\rWorkerMessage\x125\n" +
	"\x05hello\x18\x01 \x01(\v2\x1d.forge.control.v1.WorkerHelloH\x00R\x05hello\x125\n" +
	"\x05stats\x18\x02 \x01(\v2\x1d.forge.control.v1.WorkerStatsH\x00R\x05stats\x120\n" +
	"\x03ack\x18\x03 \x01(\v2\x1c.forge.control.v1.CommandAckH\x00R\x03ackB\x05\n" +
	"\x03msg\"\x90\x01\n" +
	"\vWorkerHello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\x12\x14\n" +
	"\x05types\x18\x05 \x03(\tR\x05types\"\x95\x01\n" +
	"\vWorkerStats\x12\x16\n" +
	"\x06active\x18\x01 \x01(\x05R\x06active\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\x12\x1c\n" +
	"\tprocessed\x18\x03 \x01(\x04R\tprocessed\x12 \n" +
	"\vutilization\x18\x04 \x01(\x01R\vutilization\x12\x16\n" +
	"\x06paused\x18\x05 \x01(\bR\x06paused\"C\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x92\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12/\n" +
	"\x05drain\x18\x02 \x01(\v2\x17.forge.control.v1.DrainH\x00R\x05drain\x12/\n" +
	"\x05pause\x18\x03 \x01(\v2\x17.forge.control.v1.PauseH\x00R\x05pause\x122\n" +
	"\x06resume\x18\x04 \x01(\v2\x18.forge.control.v1.ResumeH\x00R\x06resume\x12K\n" +
	"\x0fset_concurrency\x18\x05 \x01(\v2 .forge.control.v1.SetConcurrencyH\x00R\x0esetConcurrencyB\x05\n" +
	"\x03cmd\"\a\n" +
	"\x05Drain\"\a\n" +
	"\x05Pause\"\b\n" +
	"\x06Resume\"(\n" +
	"\x0eSetConcurrency\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x05R\x06target2Y\n" +
	"\aControl\x12N\n" +
	"\fWorkerStream\x12\x1f.forge.control.v1.WorkerMessage\x1a\x19.forge.control.v1.Command(\x010\x01B0Z.github.com/jguapp/forge/internal/control/pb;pbb\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_control_proto_goTypes = []any{
	(*WorkerMessage)(nil),  // 0: forge.control.v1.WorkerMessage
	(*WorkerHello)(nil),    // 1: forge.control.v1.WorkerHello
	(*WorkerStats)(nil),    // 2: forge.control.v1.WorkerStats
	(*CommandAck)(nil),     // 3: forge.control.v1.CommandAck
	(*Command)(nil),        // 4: forge.control.v1.Command
	(*Drain)(nil),          // 5: forge.control.v1.Drain
	(*Pause)(nil),          // 6: forge.control.v1.Pause
	(*Resume)(nil),         // 7: forge.control.v1.Resume
	(*SetConcurrency)(nil), // 8: forge.control.v1.SetConcurrency
}
var file_proto_control_proto_depIdxs = []int32{
	1, // 0: forge.control.v1.WorkerMessage.hello:type_name -> forge.control.v1.WorkerHello
	2, // 1: forge.control.v1.WorkerMessage.stats:type_name -> forge.control.v1.WorkerStats
	3, // 2: forge.control.v1.WorkerMessage.ack:type_name -> forge.control.v1.CommandAck
	5, // 3: forge.control.v1.Command.drain:type_name -> forge.control.v1.Drain
	6, // 4: forge.control.v1.Command.pause:type_name -> forge.control.v1.Pause
	7, // 5: forge.control.v1.Command.resume:type_name -> forge.control.v1.Resume
	8, // 6: forge.control.v1.Command.set_concurrency:type_name -> forge.control.v1.SetConcurrency
	0, // 7: forge.control.v1.Control.WorkerStream:input_type -> forge.control.v1.WorkerMessage
	4, // 8: forge.control.v1.Control.WorkerStream:output_type -> forge.control.v1.Command
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	file_proto_control_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Stats)(nil),
		(*WorkerMessage_Ack)(nil),
	}
	file_proto_control_proto_msgTypes[4].OneofWrappers = []any{
		(*Command_Drain)(nil),
		(*Command_Pause)(nil),
		(*Command_Resume)(nil),
		(*Command_SetConcurrency)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
